@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Atores humanos
Person(usuario, "Usuário", "Pessoa que utiliza o app para solicitar e interagir com veículos autônomos")

' Sistema principal
System(sistema, "Sistema de Transporte Autônomo", "Plataforma que gerencia solicitações, rotas, energia e interação com usuários")

' Sistemas externos
System_Ext(apiTrafego, "API de Tráfego", "Fornece dados de trânsito em tempo real")
System_Ext(apiClima, "API de Clima", "Fornece condições meteorológicas atuais")
System_Ext(servicoDePagamentos, "Sistema de Pagamentos", "Processa pagamentos das corridas")


' Relacionamentos
Rel(usuario, sistema, "Solicita corridas, valida veículos e recebe estimativas/instruções por voz")

Rel(sistema, apiTrafego, "Consulta dados de tráfego para calcular rotas otimizadas")
Rel(sistema, apiClima, "Consulta dados meteorológicos para ajustar as rotas")
Rel(sistema, servicoDePagamentos, "Envia informações para processar o pagamento das corridas")
@enduml